# Form implementation generated from reading ui file '/home/colin/Python/Projects/Pycharm/Development/Repositories/note-manager/src/gui/ui/management/components/DialogCreateNote/DialogCreateNote.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogCreateNote(object):
    def setupUi(self, DialogCreateNote):
        DialogCreateNote.setObjectName("DialogCreateNote")
        DialogCreateNote.resize(800, 631)
        self.TitleWidget = QtWidgets.QWidget(parent=DialogCreateNote)
        self.TitleWidget.setGeometry(QtCore.QRect(10, 10, 781, 41))
        self.TitleWidget.setObjectName("TitleWidget")
        self.HeadlineLabel = QtWidgets.QLabel(parent=self.TitleWidget)
        self.HeadlineLabel.setGeometry(QtCore.QRect(10, 10, 67, 17))
        self.HeadlineLabel.setObjectName("HeadlineLabel")
        self.DialogCreatorWidget = QtWidgets.QWidget(parent=DialogCreateNote)
        self.DialogCreatorWidget.setGeometry(QtCore.QRect(10, 160, 781, 461))
        self.DialogCreatorWidget.setObjectName("DialogCreatorWidget")
        self.WhatIsYourNewNoteNameLabel = QtWidgets.QLabel(parent=self.DialogCreatorWidget)
        self.WhatIsYourNewNoteNameLabel.setGeometry(QtCore.QRect(10, 10, 67, 17))
        self.WhatIsYourNewNoteNameLabel.setObjectName("WhatIsYourNewNoteNameLabel")
        self.NoteNamelineEdit = QtWidgets.QLineEdit(parent=self.DialogCreatorWidget)
        self.NoteNamelineEdit.setGeometry(QtCore.QRect(10, 40, 761, 41))
        self.NoteNamelineEdit.setObjectName("NoteNamelineEdit")
        self.AddNoteButton = QtWidgets.QPushButton(parent=self.DialogCreatorWidget)
        self.AddNoteButton.setGeometry(QtCore.QRect(10, 410, 761, 41))
        self.AddNoteButton.setObjectName("AddNoteButton")
        self.NoteBodytextEdit = QtWidgets.QTextEdit(parent=self.DialogCreatorWidget)
        self.NoteBodytextEdit.setGeometry(QtCore.QRect(10, 200, 761, 201))
        self.NoteBodytextEdit.setObjectName("NoteBodytextEdit")
        self.WhatIsYourNewNoteDescription = QtWidgets.QLabel(parent=self.DialogCreatorWidget)
        self.WhatIsYourNewNoteDescription.setGeometry(QtCore.QRect(10, 180, 67, 17))
        self.WhatIsYourNewNoteDescription.setObjectName("WhatIsYourNewNoteDescription")
        self.SelectParentNotebook = QtWidgets.QLabel(parent=self.DialogCreatorWidget)
        self.SelectParentNotebook.setGeometry(QtCore.QRect(10, 100, 67, 17))
        self.SelectParentNotebook.setObjectName("SelectParentNotebook")
        self.ParentNotebookSelector = QtWidgets.QComboBox(parent=self.DialogCreatorWidget)
        self.ParentNotebookSelector.setGeometry(QtCore.QRect(10, 120, 761, 41))
        self.ParentNotebookSelector.setObjectName("ParentNotebookSelector")
        self.widget = QtWidgets.QWidget(parent=DialogCreateNote)
        self.widget.setGeometry(QtCore.QRect(10, 60, 781, 91))
        self.widget.setObjectName("widget")
        self.DialogDescriptionText = QtWidgets.QLabel(parent=self.widget)
        self.DialogDescriptionText.setGeometry(QtCore.QRect(10, 10, 67, 17))
        self.DialogDescriptionText.setObjectName("DialogDescriptionText")

        self.retranslateUi(DialogCreateNote)
        QtCore.QMetaObject.connectSlotsByName(DialogCreateNote)

    def retranslateUi(self, DialogCreateNote):
        _translate = QtCore.QCoreApplication.translate
        DialogCreateNote.setWindowTitle(_translate("DialogCreateNote", "Dialog"))
        self.HeadlineLabel.setText(_translate("DialogCreateNote", "TextLabel"))
        self.WhatIsYourNewNoteNameLabel.setText(_translate("DialogCreateNote", "TextLabel"))
        self.AddNoteButton.setText(_translate("DialogCreateNote", "Add"))
        self.WhatIsYourNewNoteDescription.setText(_translate("DialogCreateNote", "TextLabel"))
        self.SelectParentNotebook.setText(_translate("DialogCreateNote", "TextLabel"))
        self.DialogDescriptionText.setText(_translate("DialogCreateNote", "TextLabel"))
