# Form implementation generated from reading ui file '/home/colin/Python/Projects/Pycharm/Development/Repositories/note-manager/src/gui/ui/management/components/DialogCreateNote/DialogCreateNote.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogCreateNote(object):
    def setupUi(self, DialogCreateNote):
        DialogCreateNote.setObjectName("DialogCreateNote")
        DialogCreateNote.resize(800, 598)
        self.TitleWidget = QtWidgets.QWidget(parent=DialogCreateNote)
        self.TitleWidget.setGeometry(QtCore.QRect(10, 10, 781, 41))
        self.TitleWidget.setObjectName("TitleWidget")
        self.HeadlineLabel = QtWidgets.QLabel(parent=self.TitleWidget)
        self.HeadlineLabel.setGeometry(QtCore.QRect(10, 10, 67, 17))
        self.HeadlineLabel.setObjectName("HeadlineLabel")
        self.DialogCreatorWidget = QtWidgets.QWidget(parent=DialogCreateNote)
        self.DialogCreatorWidget.setGeometry(QtCore.QRect(10, 160, 781, 431))
        self.DialogCreatorWidget.setObjectName("DialogCreatorWidget")
        self.WhatIsYourNewNoteNameLabel = QtWidgets.QLabel(parent=self.DialogCreatorWidget)
        self.WhatIsYourNewNoteNameLabel.setGeometry(QtCore.QRect(10, 10, 67, 17))
        self.WhatIsYourNewNoteNameLabel.setObjectName("WhatIsYourNewNoteNameLabel")
        self.NewNoteNamelineEdit = QtWidgets.QLineEdit(parent=self.DialogCreatorWidget)
        self.NewNoteNamelineEdit.setGeometry(QtCore.QRect(10, 40, 761, 41))
        self.NewNoteNamelineEdit.setObjectName("NewNoteNamelineEdit")
        self.AddNoteButton = QtWidgets.QPushButton(parent=self.DialogCreatorWidget)
        self.AddNoteButton.setGeometry(QtCore.QRect(10, 380, 761, 41))
        self.AddNoteButton.setObjectName("AddNoteButton")
        self.NewNoteBodytextEdit = QtWidgets.QTextEdit(parent=self.DialogCreatorWidget)
        self.NewNoteBodytextEdit.setGeometry(QtCore.QRect(10, 140, 761, 211))
        self.NewNoteBodytextEdit.setObjectName("NewNoteBodytextEdit")
        self.WhatIsYourNewNoteDescription = QtWidgets.QLabel(parent=self.DialogCreatorWidget)
        self.WhatIsYourNewNoteDescription.setGeometry(QtCore.QRect(10, 110, 67, 17))
        self.WhatIsYourNewNoteDescription.setObjectName("WhatIsYourNewNoteDescription")
        self.widget = QtWidgets.QWidget(parent=DialogCreateNote)
        self.widget.setGeometry(QtCore.QRect(10, 60, 781, 91))
        self.widget.setObjectName("widget")
        self.DialogDescriptionText = QtWidgets.QLabel(parent=self.widget)
        self.DialogDescriptionText.setGeometry(QtCore.QRect(10, 10, 67, 17))
        self.DialogDescriptionText.setObjectName("DialogDescriptionText")

        self.retranslateUi(DialogCreateNote)
        QtCore.QMetaObject.connectSlotsByName(DialogCreateNote)

    def retranslateUi(self, DialogCreateNote):
        _translate = QtCore.QCoreApplication.translate
        DialogCreateNote.setWindowTitle(_translate("DialogCreateNote", "Dialog"))
        self.HeadlineLabel.setText(_translate("DialogCreateNote", "TextLabel"))
        self.WhatIsYourNewNoteNameLabel.setText(_translate("DialogCreateNote", "TextLabel"))
        self.AddNoteButton.setText(_translate("DialogCreateNote", "Add"))
        self.WhatIsYourNewNoteDescription.setText(_translate("DialogCreateNote", "TextLabel"))
        self.DialogDescriptionText.setText(_translate("DialogCreateNote", "TextLabel"))
