# Form implementation generated from reading ui file '/home/colin/Python/Projects/Pycharm/Development/Repositories/note-manager/src/gui/ui/management/components/DialogCreateNotebook/DialogCreateNotebook.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogCreateNotebook(object):
    def setupUi(self, DialogCreateNotebook):
        DialogCreateNotebook.setObjectName("DialogCreateNotebook")
        DialogCreateNotebook.resize(800, 196)
        self.DialogWidget = QtWidgets.QWidget(parent=DialogCreateNotebook)
        self.DialogWidget.setGeometry(QtCore.QRect(0, 0, 801, 191))
        self.DialogWidget.setObjectName("DialogWidget")
        self.TitleWidget = QtWidgets.QWidget(parent=self.DialogWidget)
        self.TitleWidget.setGeometry(QtCore.QRect(10, 10, 781, 41))
        self.TitleWidget.setObjectName("TitleWidget")
        self.HeadlineLabel = QtWidgets.QLabel(parent=self.TitleWidget)
        self.HeadlineLabel.setGeometry(QtCore.QRect(10, 10, 67, 17))
        self.HeadlineLabel.setObjectName("HeadlineLabel")
        self.DialogCreatorWidget = QtWidgets.QWidget(parent=self.DialogWidget)
        self.DialogCreatorWidget.setGeometry(QtCore.QRect(10, 70, 781, 111))
        self.DialogCreatorWidget.setObjectName("DialogCreatorWidget")
        self.WhatIsYourNotebookNameLabel = QtWidgets.QLabel(parent=self.DialogCreatorWidget)
        self.WhatIsYourNotebookNameLabel.setGeometry(QtCore.QRect(10, 10, 67, 17))
        self.WhatIsYourNotebookNameLabel.setObjectName("WhatIsYourNotebookNameLabel")
        self.NotebookNamelineEdit = QtWidgets.QLineEdit(parent=self.DialogCreatorWidget)
        self.NotebookNamelineEdit.setGeometry(QtCore.QRect(10, 40, 701, 41))
        self.NotebookNamelineEdit.setObjectName("NotebookNamelineEdit")
        self.AddNotebookButton = QtWidgets.QPushButton(parent=self.DialogCreatorWidget)
        self.AddNotebookButton.setGeometry(QtCore.QRect(720, 40, 51, 41))
        self.AddNotebookButton.setObjectName("AddNotebookButton")

        self.retranslateUi(DialogCreateNotebook)
        QtCore.QMetaObject.connectSlotsByName(DialogCreateNotebook)

    def retranslateUi(self, DialogCreateNotebook):
        _translate = QtCore.QCoreApplication.translate
        DialogCreateNotebook.setWindowTitle(_translate("DialogCreateNotebook", "Dialog"))
        self.HeadlineLabel.setText(_translate("DialogCreateNotebook", "TextLabel"))
        self.WhatIsYourNotebookNameLabel.setText(_translate("DialogCreateNotebook", "TextLabel"))
        self.AddNotebookButton.setText(_translate("DialogCreateNotebook", "Add"))
