# Form implementation generated from reading ui file '/home/colin/Python/Projects/Pycharm/Development/Repositories/note-manager/src/gui/ui/dialogs/DialogCreateNotebook/DialogCreateNotebook.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogCreateNotebook(object):
    def setupUi(self, DialogCreateNotebook):
        DialogCreateNotebook.setObjectName("DialogCreateNotebook")
        DialogCreateNotebook.resize(800, 164)
        self.DialogWidget = QtWidgets.QWidget(parent=DialogCreateNotebook)
        self.DialogWidget.setGeometry(QtCore.QRect(0, 0, 801, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DialogWidget.sizePolicy().hasHeightForWidth())
        self.DialogWidget.setSizePolicy(sizePolicy)
        self.DialogWidget.setObjectName("DialogWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.DialogWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.creatorWidget = QtWidgets.QWidget(parent=self.DialogWidget)
        self.creatorWidget.setMinimumSize(QtCore.QSize(0, 80))
        self.creatorWidget.setMaximumSize(QtCore.QSize(16777215, 90))
        self.creatorWidget.setObjectName("creatorWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.creatorWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.NotebookName_lineEdit = QtWidgets.QLineEdit(parent=self.creatorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NotebookName_lineEdit.sizePolicy().hasHeightForWidth())
        self.NotebookName_lineEdit.setSizePolicy(sizePolicy)
        self.NotebookName_lineEdit.setObjectName("NotebookName_lineEdit")
        self.gridLayout_2.addWidget(self.NotebookName_lineEdit, 2, 0, 1, 1)
        self.AddNotebookButton = QtWidgets.QPushButton(parent=self.creatorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddNotebookButton.sizePolicy().hasHeightForWidth())
        self.AddNotebookButton.setSizePolicy(sizePolicy)
        self.AddNotebookButton.setMinimumSize(QtCore.QSize(0, 0))
        self.AddNotebookButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.AddNotebookButton.setObjectName("AddNotebookButton")
        self.gridLayout_2.addWidget(self.AddNotebookButton, 2, 1, 1, 1)
        self.WhatIsYourNotebookNameLabel = QtWidgets.QLabel(parent=self.creatorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WhatIsYourNotebookNameLabel.sizePolicy().hasHeightForWidth())
        self.WhatIsYourNotebookNameLabel.setSizePolicy(sizePolicy)
        self.WhatIsYourNotebookNameLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.WhatIsYourNotebookNameLabel.setObjectName("WhatIsYourNotebookNameLabel")
        self.gridLayout_2.addWidget(self.WhatIsYourNotebookNameLabel, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.creatorWidget, 1, 0, 1, 1)
        self.TitleWidget = QtWidgets.QWidget(parent=self.DialogWidget)
        self.TitleWidget.setMinimumSize(QtCore.QSize(0, 40))
        self.TitleWidget.setMaximumSize(QtCore.QSize(16777215, 40))
        self.TitleWidget.setObjectName("TitleWidget")
        self.HeadlineLabel = QtWidgets.QLabel(parent=self.TitleWidget)
        self.HeadlineLabel.setGeometry(QtCore.QRect(10, 10, 67, 17))
        self.HeadlineLabel.setObjectName("HeadlineLabel")
        self.gridLayout.addWidget(self.TitleWidget, 0, 0, 1, 1)

        self.retranslateUi(DialogCreateNotebook)
        QtCore.QMetaObject.connectSlotsByName(DialogCreateNotebook)

    def retranslateUi(self, DialogCreateNotebook):
        _translate = QtCore.QCoreApplication.translate
        DialogCreateNotebook.setWindowTitle(_translate("DialogCreateNotebook", "Dialog"))
        self.AddNotebookButton.setText(_translate("DialogCreateNotebook", "Add"))
        self.WhatIsYourNotebookNameLabel.setText(_translate("DialogCreateNotebook", "TextLabel"))
        self.HeadlineLabel.setText(_translate("DialogCreateNotebook", "TextLabel"))
