# Form implementation generated from reading ui file '/home/colin/Python/Projects/Pycharm/Development/Repositories/note-manager/src/gui/ui/dialogs/OpenedNoteDialog/OpenedNote.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OpenedNoteDialog(object):
    def setupUi(self, OpenedNoteDialog):
        OpenedNoteDialog.setObjectName("OpenedNoteDialog")
        OpenedNoteDialog.resize(821, 706)
        OpenedNoteDialog.setMinimumSize(QtCore.QSize(0, 706))
        self.gridLayout = QtWidgets.QGridLayout(OpenedNoteDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.TitleWidget = QtWidgets.QWidget(parent=OpenedNoteDialog)
        self.TitleWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TitleWidget.sizePolicy().hasHeightForWidth())
        self.TitleWidget.setSizePolicy(sizePolicy)
        self.TitleWidget.setMaximumSize(QtCore.QSize(16777215, 65))
        self.TitleWidget.setAutoFillBackground(False)
        self.TitleWidget.setObjectName("TitleWidget")
        self.noteTitle_lineEdit = QtWidgets.QLineEdit(parent=self.TitleWidget)
        self.noteTitle_lineEdit.setGeometry(QtCore.QRect(0, 20, 801, 41))
        self.noteTitle_lineEdit.setObjectName("noteTitle_lineEdit")
        self.noteTitle_label = QtWidgets.QLabel(parent=self.TitleWidget)
        self.noteTitle_label.setGeometry(QtCore.QRect(0, 0, 67, 17))
        self.noteTitle_label.setObjectName("noteTitle_label")
        self.gridLayout.addWidget(self.TitleWidget, 0, 0, 1, 1)
        self.selectorWidget = QtWidgets.QWidget(parent=OpenedNoteDialog)
        self.selectorWidget.setMaximumSize(QtCore.QSize(16777215, 75))
        self.selectorWidget.setObjectName("selectorWidget")
        self.selector_comboBox = QtWidgets.QComboBox(parent=self.selectorWidget)
        self.selector_comboBox.setGeometry(QtCore.QRect(0, 30, 801, 41))
        self.selector_comboBox.setObjectName("selector_comboBox")
        self.selector_label = QtWidgets.QLabel(parent=self.selectorWidget)
        self.selector_label.setGeometry(QtCore.QRect(0, 10, 67, 17))
        self.selector_label.setObjectName("selector_label")
        self.gridLayout.addWidget(self.selectorWidget, 1, 0, 1, 1)
        self.DescriptionWidget = QtWidgets.QWidget(parent=OpenedNoteDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DescriptionWidget.sizePolicy().hasHeightForWidth())
        self.DescriptionWidget.setSizePolicy(sizePolicy)
        self.DescriptionWidget.setMaximumSize(QtCore.QSize(16777215, 560))
        self.DescriptionWidget.setObjectName("DescriptionWidget")
        self.noteDescription_textEdit = QtWidgets.QTextEdit(parent=self.DescriptionWidget)
        self.noteDescription_textEdit.setGeometry(QtCore.QRect(0, 30, 801, 501))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noteDescription_textEdit.sizePolicy().hasHeightForWidth())
        self.noteDescription_textEdit.setSizePolicy(sizePolicy)
        self.noteDescription_textEdit.setMaximumSize(QtCore.QSize(16777215, 560))
        self.noteDescription_textEdit.setObjectName("noteDescription_textEdit")
        self.noteDescription_label = QtWidgets.QLabel(parent=self.DescriptionWidget)
        self.noteDescription_label.setGeometry(QtCore.QRect(0, 10, 67, 17))
        self.noteDescription_label.setObjectName("noteDescription_label")
        self.gridLayout.addWidget(self.DescriptionWidget, 2, 0, 1, 1)

        self.retranslateUi(OpenedNoteDialog)
        QtCore.QMetaObject.connectSlotsByName(OpenedNoteDialog)

    def retranslateUi(self, OpenedNoteDialog):
        _translate = QtCore.QCoreApplication.translate
        OpenedNoteDialog.setWindowTitle(_translate("OpenedNoteDialog", "Dialog"))
        self.noteTitle_label.setText(_translate("OpenedNoteDialog", "TextLabel"))
        self.selector_label.setText(_translate("OpenedNoteDialog", "TextLabel"))
        self.noteDescription_label.setText(_translate("OpenedNoteDialog", "TextLabel"))
