# Form implementation generated from reading ui file '/home/colin/Python/Projects/Pycharm/Development/Repositories/note-manager/src/gui/ui/dialogs/OptionsDialogCreate/OptionsDialogCreate.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OptionsDialogCreate(object):
    def setupUi(self, OptionsDialogCreate):
        OptionsDialogCreate.setObjectName("OptionsDialogCreate")
        OptionsDialogCreate.resize(472, 322)
        self.DialogWidget = QtWidgets.QWidget(parent=OptionsDialogCreate)
        self.DialogWidget.setGeometry(QtCore.QRect(0, 0, 471, 321))
        self.DialogWidget.setObjectName("DialogWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.DialogWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonWidget = QtWidgets.QWidget(parent=self.DialogWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonWidget.sizePolicy().hasHeightForWidth())
        self.buttonWidget.setSizePolicy(sizePolicy)
        self.buttonWidget.setMinimumSize(QtCore.QSize(456, 0))
        self.buttonWidget.setMaximumSize(QtCore.QSize(456, 16777215))
        self.buttonWidget.setObjectName("buttonWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.buttonWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CreateNotebookButton = QtWidgets.QPushButton(parent=self.buttonWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CreateNotebookButton.sizePolicy().hasHeightForWidth())
        self.CreateNotebookButton.setSizePolicy(sizePolicy)
        self.CreateNotebookButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.CreateNotebookButton.setObjectName("CreateNotebookButton")
        self.verticalLayout.addWidget(self.CreateNotebookButton)
        self.CreateNoteButton = QtWidgets.QPushButton(parent=self.buttonWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CreateNoteButton.sizePolicy().hasHeightForWidth())
        self.CreateNoteButton.setSizePolicy(sizePolicy)
        self.CreateNoteButton.setObjectName("CreateNoteButton")
        self.verticalLayout.addWidget(self.CreateNoteButton)
        self.gridLayout.addWidget(self.buttonWidget, 4, 0, 1, 1)
        self.contentWidget = QtWidgets.QWidget(parent=self.DialogWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contentWidget.sizePolicy().hasHeightForWidth())
        self.contentWidget.setSizePolicy(sizePolicy)
        self.contentWidget.setMinimumSize(QtCore.QSize(456, 0))
        self.contentWidget.setMaximumSize(QtCore.QSize(456, 60))
        self.contentWidget.setObjectName("contentWidget")
        self.gridLayout.addWidget(self.contentWidget, 3, 0, 1, 1)
        self.TitleWidget = QtWidgets.QWidget(parent=self.DialogWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TitleWidget.sizePolicy().hasHeightForWidth())
        self.TitleWidget.setSizePolicy(sizePolicy)
        self.TitleWidget.setMinimumSize(QtCore.QSize(456, 20))
        self.TitleWidget.setMaximumSize(QtCore.QSize(16777215, 40))
        self.TitleWidget.setObjectName("TitleWidget")
        self.HeadlineLabel = QtWidgets.QLabel(parent=self.TitleWidget)
        self.HeadlineLabel.setGeometry(QtCore.QRect(10, 20, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.HeadlineLabel.setFont(font)
        self.HeadlineLabel.setObjectName("HeadlineLabel")
        self.gridLayout.addWidget(self.TitleWidget, 2, 0, 1, 1)

        self.retranslateUi(OptionsDialogCreate)
        QtCore.QMetaObject.connectSlotsByName(OptionsDialogCreate)

    def retranslateUi(self, OptionsDialogCreate):
        _translate = QtCore.QCoreApplication.translate
        OptionsDialogCreate.setWindowTitle(_translate("OptionsDialogCreate", "Dialog"))
        self.CreateNotebookButton.setText(_translate("OptionsDialogCreate", "PushButton"))
        self.CreateNoteButton.setText(_translate("OptionsDialogCreate", "PushButton"))
        self.HeadlineLabel.setText(_translate("OptionsDialogCreate", "TextLabel"))
