# Form implementation generated from reading ui file '/home/colin/Python/Projects/Pycharm/Development/Repositories/note-manager/src/gui/ui/notes/OverviewWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OverviewWindow(object):
    def setupUi(self, OverviewWindow):
        OverviewWindow.setObjectName("OverviewWindow")
        OverviewWindow.resize(800, 600)
        self.WindowWidget = QtWidgets.QWidget(parent=OverviewWindow)
        self.WindowWidget.setObjectName("WindowWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.WindowWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(parent=self.WindowWidget)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 3, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setObjectName("widget_2")
        self.tableView = QtWidgets.QTableView(parent=self.widget_2)
        self.tableView.setGeometry(QtCore.QRect(0, 0, 761, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setObjectName("tableView")
        self.gridLayout_3.addWidget(self.widget_2, 2, 1, 1, 5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 3, 4, 1, 1)
        self.WindowTitleWidget = QtWidgets.QWidget(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WindowTitleWidget.sizePolicy().hasHeightForWidth())
        self.WindowTitleWidget.setSizePolicy(sizePolicy)
        self.WindowTitleWidget.setMinimumSize(QtCore.QSize(0, 40))
        self.WindowTitleWidget.setObjectName("WindowTitleWidget")
        self.WindowTitleLabel = QtWidgets.QLabel(parent=self.WindowTitleWidget)
        self.WindowTitleLabel.setGeometry(QtCore.QRect(10, 10, 67, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WindowTitleLabel.sizePolicy().hasHeightForWidth())
        self.WindowTitleLabel.setSizePolicy(sizePolicy)
        self.WindowTitleLabel.setObjectName("WindowTitleLabel")
        self.gridLayout_3.addWidget(self.WindowTitleWidget, 0, 1, 1, 5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 3, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.gridLayout_3.addItem(spacerItem3, 1, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 3, 5, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 3, 3, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        OverviewWindow.setCentralWidget(self.WindowWidget)

        self.retranslateUi(OverviewWindow)
        QtCore.QMetaObject.connectSlotsByName(OverviewWindow)

    def retranslateUi(self, OverviewWindow):
        _translate = QtCore.QCoreApplication.translate
        OverviewWindow.setWindowTitle(_translate("OverviewWindow", "MainWindow"))
        self.WindowTitleLabel.setText(_translate("OverviewWindow", "TextLabel"))
