# Form implementation generated from reading ui file '/home/colin/Python/Projects/Pycharm/Development/Repositories/note-manager/src/gui/ui/dialogs/DialogManageNotes/DialogManageNotes.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogManageNotes(object):
    def setupUi(self, DialogManageNotes):
        DialogManageNotes.setObjectName("DialogManageNotes")
        DialogManageNotes.resize(641, 410)
        self.gridLayout = QtWidgets.QGridLayout(DialogManageNotes)
        self.gridLayout.setObjectName("gridLayout")
        self.introductionWidget = QtWidgets.QWidget(parent=DialogManageNotes)
        self.introductionWidget.setMaximumSize(QtCore.QSize(16777215, 60))
        self.introductionWidget.setObjectName("introductionWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.introductionWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.introductionWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.introductionWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout.addWidget(self.introductionWidget, 0, 0, 1, 1)
        self.contentWidget = QtWidgets.QWidget(parent=DialogManageNotes)
        self.contentWidget.setMaximumSize(QtCore.QSize(16777215, 300))
        self.contentWidget.setObjectName("contentWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contentWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.contentWidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableView = QtWidgets.QTableView(parent=self.frame)
        self.tableView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableView.setObjectName("tableView")
        self.verticalLayout_3.addWidget(self.tableView)
        self.verticalLayout_2.addWidget(self.frame)
        self.gridLayout.addWidget(self.contentWidget, 1, 0, 1, 1)
        self.buttonWidget = QtWidgets.QWidget(parent=DialogManageNotes)
        self.buttonWidget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.buttonWidget.setObjectName("buttonWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.buttonWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.buttonWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.buttonWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.buttonWidget, 2, 0, 1, 1)

        self.retranslateUi(DialogManageNotes)
        QtCore.QMetaObject.connectSlotsByName(DialogManageNotes)

    def retranslateUi(self, DialogManageNotes):
        _translate = QtCore.QCoreApplication.translate
        DialogManageNotes.setWindowTitle(_translate("DialogManageNotes", "Dialog"))
        self.label.setText(_translate("DialogManageNotes", "TextLabel"))
        self.label_2.setText(_translate("DialogManageNotes", "TextLabel"))
        self.pushButton_2.setText(_translate("DialogManageNotes", "PushButton"))
        self.pushButton.setText(_translate("DialogManageNotes", "PushButton"))
