# Form implementation generated from reading ui file '/home/colin/Python/Projects/Pycharm/Development/Repositories/note-manager/src/gui/ui/dialogs/DialogEditNotebook/DialogEditNotebook.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogEditNotebook(object):
    def setupUi(self, DialogEditNotebook):
        DialogEditNotebook.setObjectName("DialogEditNotebook")
        DialogEditNotebook.resize(800, 169)
        self.dialogWidget = QtWidgets.QWidget(parent=DialogEditNotebook)
        self.dialogWidget.setGeometry(QtCore.QRect(0, 0, 801, 164))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dialogWidget.sizePolicy().hasHeightForWidth())
        self.dialogWidget.setSizePolicy(sizePolicy)
        self.dialogWidget.setObjectName("dialogWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.dialogWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.titleWidget = QtWidgets.QWidget(parent=self.dialogWidget)
        self.titleWidget.setMinimumSize(QtCore.QSize(100, 40))
        self.titleWidget.setMaximumSize(QtCore.QSize(16777215, 40))
        self.titleWidget.setObjectName("titleWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.titleWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.headlineLabel = QtWidgets.QLabel(parent=self.titleWidget)
        self.headlineLabel.setObjectName("headlineLabel")
        self.gridLayout_3.addWidget(self.headlineLabel, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.titleWidget, 0, 0, 1, 1)
        self.editorWidget = QtWidgets.QWidget(parent=self.dialogWidget)
        self.editorWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.editorWidget.setMaximumSize(QtCore.QSize(16777215, 90))
        self.editorWidget.setObjectName("editorWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.editorWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.notebookName_lineEdit = QtWidgets.QLineEdit(parent=self.editorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notebookName_lineEdit.sizePolicy().hasHeightForWidth())
        self.notebookName_lineEdit.setSizePolicy(sizePolicy)
        self.notebookName_lineEdit.setObjectName("notebookName_lineEdit")
        self.gridLayout_2.addWidget(self.notebookName_lineEdit, 2, 0, 1, 1)
        self.saveChangesButton = QtWidgets.QPushButton(parent=self.editorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveChangesButton.sizePolicy().hasHeightForWidth())
        self.saveChangesButton.setSizePolicy(sizePolicy)
        self.saveChangesButton.setMinimumSize(QtCore.QSize(0, 0))
        self.saveChangesButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.saveChangesButton.setObjectName("saveChangesButton")
        self.gridLayout_2.addWidget(self.saveChangesButton, 2, 1, 1, 1)
        self.notebookNameLabel = QtWidgets.QLabel(parent=self.editorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notebookNameLabel.sizePolicy().hasHeightForWidth())
        self.notebookNameLabel.setSizePolicy(sizePolicy)
        self.notebookNameLabel.setMinimumSize(QtCore.QSize(0, 10))
        self.notebookNameLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.notebookNameLabel.setObjectName("notebookNameLabel")
        self.gridLayout_2.addWidget(self.notebookNameLabel, 1, 0, 1, 2)
        self.gridLayout.addWidget(self.editorWidget, 1, 0, 1, 1)

        self.retranslateUi(DialogEditNotebook)
        QtCore.QMetaObject.connectSlotsByName(DialogEditNotebook)

    def retranslateUi(self, DialogEditNotebook):
        _translate = QtCore.QCoreApplication.translate
        DialogEditNotebook.setWindowTitle(_translate("DialogEditNotebook", "Dialog"))
        self.headlineLabel.setText(_translate("DialogEditNotebook", "TextLabel"))
        self.saveChangesButton.setText(_translate("DialogEditNotebook", "pushButton"))
        self.notebookNameLabel.setText(_translate("DialogEditNotebook", "TextLabel"))
