# Form implementation generated from reading ui file '/home/colin/Python/Projects/Pycharm/Development/Repositories/note-manager/src/gui/ui/management/components/OptionsDialogCreate/OptionsDialogCreate.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OptionsDialogCreate(object):
    def setupUi(self, OptionsDialogCreate):
        OptionsDialogCreate.setObjectName("OptionsDialogCreate")
        OptionsDialogCreate.resize(400, 300)
        self.DialogWidget = QtWidgets.QWidget(parent=OptionsDialogCreate)
        self.DialogWidget.setGeometry(QtCore.QRect(0, 0, 401, 301))
        self.DialogWidget.setObjectName("DialogWidget")
        self.TitleWidget = QtWidgets.QWidget(parent=self.DialogWidget)
        self.TitleWidget.setGeometry(QtCore.QRect(10, 10, 381, 41))
        self.TitleWidget.setObjectName("TitleWidget")
        self.HeadlineLabel = QtWidgets.QLabel(parent=self.TitleWidget)
        self.HeadlineLabel.setGeometry(QtCore.QRect(10, 10, 67, 17))
        self.HeadlineLabel.setObjectName("HeadlineLabel")
        self.widget = QtWidgets.QWidget(parent=self.DialogWidget)
        self.widget.setGeometry(QtCore.QRect(10, 110, 381, 181))
        self.widget.setObjectName("widget")
        self.CreateNoteGroupButton = QtWidgets.QPushButton(parent=self.widget)
        self.CreateNoteGroupButton.setGeometry(QtCore.QRect(0, 0, 381, 91))
        self.CreateNoteGroupButton.setObjectName("CreateNoteGroupButton")
        self.CreateNoteButton = QtWidgets.QPushButton(parent=self.widget)
        self.CreateNoteButton.setGeometry(QtCore.QRect(0, 90, 381, 91))
        self.CreateNoteButton.setObjectName("CreateNoteButton")

        self.retranslateUi(OptionsDialogCreate)
        QtCore.QMetaObject.connectSlotsByName(OptionsDialogCreate)

    def retranslateUi(self, OptionsDialogCreate):
        _translate = QtCore.QCoreApplication.translate
        OptionsDialogCreate.setWindowTitle(_translate("OptionsDialogCreate", "Dialog"))
        self.HeadlineLabel.setText(_translate("OptionsDialogCreate", "TextLabel"))
        self.CreateNoteGroupButton.setText(_translate("OptionsDialogCreate", "Note group"))
        self.CreateNoteButton.setText(_translate("OptionsDialogCreate", "Note"))
